QA/urls.py
from django.contrib import admin
from django.urls import path,include
from qas import views as qasview
from accounts import views as accountsview

app_name = 'in'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('questions/',include('qas.urls')),    
    path('',qasview.index,name='home'),
]

accounts/urls.py
from django.urls import path
from accounts import views


app_name = 'accounts'

urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('login/',views.login_view,name='login'),
    path('logout/',views.logout_view,name='logout')   
]

qas/urls.py
from django.urls import path,include
from qas import views


app_name = 'questions'

urlpatterns = [   
    path('questionslists/',views.index,name="questionlistis"),
    path('askquestion/',views.askquestion,name="askquestion"),
    path('<int:qids>/',views.question_detail,name="questiondetail"),
   
]

accounts/models.py
from django.db import models

# Create your models here.

qas/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Questions(models.Model):
    title = models.CharField(max_length=800)
    detail = models.TextField()
    date = models.DateField(auto_now_add=True)    
    author = models.ForeignKey(User,on_delete=models.CASCADE,default=None)
    
    def __str__(self):
        return self.title
    
class Solutions(models.Model):
    date = models.DateField(auto_now_add=True)
    solution = models.TextField()
    solve = models.BooleanField(default=False)
    qid = models.ForeignKey(Questions,on_delete=models.CASCADE,default=None)
    author = models.ForeignKey(User,on_delete=models.CASCADE,default=None)   
    
    def __str__(self):
        return self.solution

qas/forms.py
from django import forms
from .import models

class GiveSolution(forms.ModelForm):
    class Meta:
        model = models.Solutions
        fields = ['solution']
        
class AskQuestion(forms.ModelForm):
    class Meta:
        model = models.Questions
        fields = ['title','detail']

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login, logout


# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
           user = form.save()
           login(request,user)
           return redirect('home')        
    else:
        form = UserCreationForm
    return render(request,'accounts/signup.html',{'forms':form})

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            return redirect('home')
    else:
        form = AuthenticationForm
    return render(request,'accounts/login.html',{'form':form})

def logout_view(request):
    if request.method =="POST":
        logout(request)
        return redirect('home')    
    

qas/views.py
from django.shortcuts import render,redirect
from django.core.paginator import Paginator
from .models import Questions,Solutions
from .import forms
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):   
    questions = Questions.objects.all()
    paginator = Paginator(questions,10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request,'qas/index.html',{'questions':page_obj})

def question_detail(request,qids):
    questions = Questions.objects.get(id=qids)
    details = Solutions.objects.filter(qid=qids)
    if request.method == 'POST':          
        form = forms.GiveSolution(request.POST)
        if form.is_valid():            
            instance = form.save(commit =False)        
            instance.qid = questions
            instance.author = request.user
            instance.save()
            return redirect('questions:questiondetail',qids)
    else:
        form = forms.GiveSolution()            
    return render(request,'qas/detail.html',{'details':details,'form':form,'question':questions})

@login_required
def askquestion(request):
    if request.method == 'POST':
        form = forms.AskQuestion(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('questions:questionlistis')
    else:
        form = forms.AskQuestion()
    return render(request,'qas/askquestion.html',{'form':form})
    

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
   <form action="/accounts/login/" method="POST" class="ask-question-form">
    {% csrf_token %}
       {{form}}
       <input type="submit" value="Log in">
   </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
  
    <form action="/accounts/signup/" method="POST" class="ask-question-form">
        
        {% csrf_token %}
        {{forms}}
        <input type="submit" name="signup"  value="Sign up" id="sing-up-button">
    </form>
        
   
{% endblock %}

qas/templates/qas/askquestion.html
{% extends 'base_layout.html' %}

{% block content %}


    <form action="{% url 'questions:askquestion' %}" method="POST" class="ask-question-form">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="submit">
    </form>
   
    
{% endblock %}

qas/templates/qas/detail.html
{% extends 'base_layout.html' %}

{% block content %}

<div class="question-container"> 

    <ul>  
        <li> {{question.author}} | {{ question.date }}</li>
        <li>        
          <h1> {{question.title}} </h1>  
        </li> 
        <li>        
            {{question.detail}}
        </li>  
        
        {% for detail in details %}  
        <li>  
            <div class="solution"> 
               <h5> {{detail.author}} </h5> 
               <p> {{detail.date}}</p> 
               
               <p class="paragraph"> {{detail.solution}} </p>   
               
            </div>   
                     
        </li>   

        {% endfor %} 
        
        {% if user.is_authenticated %}

            <form action="{% url 'questions:questiondetail' qids=question.id %} " method="POST" class="detail-form">
                {% csrf_token %}                
                {{form}}                
                <input type="hidden" value="{{question.id}}" name="{{question.id}}">
                <input type="submit" value="Post">   
                
            </form>        
        
    </ul>
    {% else %}
        <h3> You need to <a href="{% url 'accounts:login' %}"> login </a>  or <a href="{% url 'accounts:signup' %}"> sign up</a>  to comment this question </h3> 
    {% endif %}
</div>

{% endblock %}

qas/templates/qas/index.html
{% extends 'base_layout.html'%}

{% block content %}

    <div class="question-container">
        {% for question in questions %}
        <ul> 
            <li> <p> {{ question.author}} </p>  </li> 
            <li> <p> Postet on : {{ question.date}}</p>  </li>           
            <li>
                <a href="{% url 'questions:questiondetail' qids=question.id %}"> 
                  <h1> {{ question.title }} </h1>
                </a>
            </li>
                {{ question.detail }}  
        </ul>

        {% endfor %}

        {% if questions.has_other_pages %}
        <ul class="pagination">
          {% if questions.has_previous %}
            <li><a href="?page={{ questions.previous_page_number }}">&laquo;</a></li>
          {% else %}
            <li class="disabled"><span>&laquo;</span></li>
          {% endif %}
          {% for i in questions.paginator.page_range %}
            {% if users.number == i %}
              <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
            {% else %}
              <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endif %}
          {% endfor %}
          {% if questions.has_next %}
            <li><a href="?page={{ questions.next_page_number }}">&raquo;</a></li>
          {% else %}
            <li class="disabled"><span>&raquo;</span></li>
          {% endif %}
        </ul>
      {% endif %}
            
    </div>
{% endblock %}

templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    <title>Q&A by HanIndustries</title>
</head>
<body>

    <nav>
        <input type="checkbox" id="check">
        <label for="check" class="checkbtn">
          <i class="fas fa-bars"></i>
        </label>
    <a href="{% url 'questions:questionlistis' %}" >
        <label for="" class="logo">
         Q&A.net     
        </label>
    </a>
        <ul class="check-ul">
            {% if user.is_authenticated %}

            <li>
                {{user}} 
            </li>
            
            <li>
                <a href="{% url 'questions:askquestion' %}">Ask Question</a>
            </li>

            <li>
                <form action="{% url 'accounts:logout' %}" method="POST">
                    {% csrf_token %}
                    <button type="submit">Log out</button>               
                </form>
            </li>
            
            {%else %}
            <li>
                <a href="{% url 'accounts:login' %}">Log In</a>
            </li>

            <li>
                <a href="{% url 'accounts:signup' %}">Sign Up</a>
            </li>
            {% endif %}
            
        </ul>
    </nav>
    
    {% block content %}

    {% endblock %}
    <script src="{% static 'jquery.js' %}"></script>
    <script src="{% static 'style.js' %}"></script>
</body>
</html>